version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15

executors:
  circleci-gauge-executor:
    docker:
      - image: circleci/node:11.9.0-browsers

workflows:
  version: 2
  test:
    jobs:
      - shellcheck/check
      - test:
          requires:
            - shellcheck/check

jobs:
  test:
    working_directory: ~/agile-pathway-co-uk
    executor: circleci-gauge-executor
    steps:
      - checkout
      - run: curl -SsL https://downloads.gauge.org/stable | sh
      - run:
          name: Define TEST_SITE_URL Environment Variable at Runtime
          command: ./.circleci/scripts/set-test-site-url.sh
      - run: cd e2etests && gauge install && npm install && npm test
      - store_artifacts:
          path: reports
