version: 2.1

orbs:
  shellcheck: circleci/shellcheck@1.3.15

executors:
  circleci-gauge-executor:
    docker:
      - image: agilepathway/cimg-gauge:1.0.8-CIRCLECI-480

workflows:
  test:
    jobs:
      - shellcheck/check
      - test

jobs:
  test:
    working_directory: ~/agile-pathway-co-uk
    executor: circleci-gauge-executor
    steps:
      - checkout
      - run: cd e2etests && npm link taiko
      - run:
          name: Define TEST_SITE_URL Environment Variable at Runtime
          command: ./.circleci/scripts/set-test-site-url.sh
      - run:
          name: Check test site is up
          command: ./.circleci/scripts/check-test-site-up.sh
      - run: cd e2etests && gauge run specs
      - store_artifacts:
          path: ./e2etests/reports/html-report/
      - store_test_results:
          path: ./e2etests/reports/xml-report/
